
package com.form;

import com.main.Config;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
    import java.sql.Connection;
    import javax.swing.table.DefaultTableModel;
    import java.sql.Statement;
    import java.sql.ResultSet;
    import java.sql.PreparedStatement;
    import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;

public class Form_5 extends javax.swing.JPanel {

   Connection conn;
   
   private DefaultTableModel model;
   
   public void load_table(){
       
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged(); 
        
        
        try{
            Connection conn = (Connection) Config.configDB();
            Statement s = conn.createStatement();
//            String sql = "SELECT DATE_FORMAT(transaksi.tgl_transaksi, '%d %b %y') AS tanggal,transaksi.no_kamar,transaksi.nama_penyewa, DATE_FORMAT(transaksi.tgl_mulai_sewa, '%d %b %y') AS tgl_mulai,DATE_FORMAT(transaksi.tgl_akhir_sewa, '%d %b %y') AS tgl_akhir,transaksi.jumlah_bulan,detail_bayar.total_harga FROM transaksi JOIN detail_bayar ON transaksi.id_transaksi = detail_bayar.id_transaksi;

            String sql ="SELECT DATE_FORMAT(transaksi.tgl_transaksi, '%d %b %y') AS tanggal, transaksi.no_kamar, transaksi.nama_penyewa, DATE_FORMAT (transaksi.tgl_mulai_sewa, '%d %b %y') AS tgl_mulai, DATE _FORMAT(transaksi.tgl_akhir_sewa, '%d %b %y') AS tgl_akhir, transaksi.jumlah_bulan, detail_bayar.total_harga FROM transaksi JOIN detail_bayar ON transaksi.id_transaksi = detail_bayar.id_transaksi"; 
            ResultSet rs = s.executeQuery(sql);
            
            while(rs.next()){
                Object[]o = new Object[7];
                o [0] = rs.getString("tanggal");
                o [1] = rs.getString("no_kamar");
                o [2] = rs.getString("nama_penyewa");
                o [3] = rs.getString("tgl_mulai");
                o [4] = rs.getString("tgl_akhir");
                o [5] = rs.getString("jumlah_bulan");
                o [6] = rs.getString("total_harga");
                
                
                
                model.addRow(o);
            }
            rs.close();
            s.close();
        }catch (SQLException e){
            System.out.println("terjadi kesalahan" + e.getMessage());
   }
   
       
//       model.getDataVector().removeAllElements();
//       model.fireTableDataChanged();
//       
//       try{
//           int q;
//         Connection conn = Config.configDB();
//         Statement s = conn.createStatement();
//         String sql = "SELECT DATE_FORMAT(transaksi.tgl_transaksi, '%d %b %y') AS tanggal, transaksi.no_kamar, transaksi.nama_penyewa, DATE_FORMAT (transaksi.tgl_mulai_sewa, '%d %b %y') AS tgal_mulai, DATE FORMAT(transaksi.tgl_akhir_sewa, '%d %b %y') AS tgl_akhir, transaksi.jumlah_bulan, detail_bayar.total_harga FROM transaksi JOIN detail_bayarON transaksi.id_transaksi = detail_bayar.id_transaksi"; 
//         PreparedStatement pst = conn.prepareStatement(sql);
//         ResultSet rs = pst.executeQuery(sql);
//           ResultSetMetaData rss = rs.getMetaData();
//           q = rss.getColumnCount();
//           
//           DefaultTableModel model = (DefaultTableModel) table.getModel();
//           model.setRowCount(0);
//           while(rs.next()){
//               Vector v2 = new Vector();
//               for(int a = 1; a <= q; a++){
//                  
//               }
//           }
       }
   
    public Form_5() {
        initComponents();
//        txtNoKamar.setEnabled(false);
        
        model = new DefaultTableModel();
        
        table_Profil1.setModel(model);
        
        model.addColumn("Tanggal");
        model.addColumn("Kamar");
        model.addColumn("Nama");
        model.addColumn("Tgl Mulai");
        model.addColumn("Tgl Akhir");
        model.addColumn("Jml Bulan");
        model.addColumn("Total Akhir");
        
        
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Profil1 = new com.swing.Table_Profil();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Riwayat Transkasi ");

        jButton1.setText("Reset");

        jScrollPane1.setViewportView(table_Profil1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.swing.Table_Profil table_Profil1;
    // End of variables declaration//GEN-END:variables
}
